package com.github.testclient.ui;

import com.github.testclient.util.AndroidDevice;

/**
 *
 * @author Ray_Zhou
 */
public class LogViewerFrame extends javax.swing.JFrame {

	private AndroidDevice device;
	/**
	 * Creates new form LogViewer
	 */
	public LogViewerFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		logScrollPane = new javax.swing.JScrollPane();
		logArea = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		logArea.setEditable(false);
		logArea.setColumns(20);
		logArea.setRows(5);
		logScrollPane.setViewportView(logArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
						.addContainerGap())
				);

		pack();
	}// </editor-fold>                        

	public void addLine(String text)
	{
		this.logArea.append(text + "\n");
		this.logArea.setCaretPosition(this.logArea.getDocument().getLength());
	}

	public void clearText()
	{
		this.logArea.setText("");
	}

	// Variables declaration - do not modify                     
	private javax.swing.JTextArea logArea;
	private javax.swing.JScrollPane logScrollPane;
	// End of variables declaration                   
}
