package com.github.testclient.ui;

import com.github.testclient.ui.components.editor.TestDataButtonEditor;

/**
*
* @author Ray_Zhou
*/
public class ViewTestDataFrame extends javax.swing.JFrame {

	private TestDataButtonEditor dataSourceEditor;
   /**
    * Creates new form TestDataFrame
    */
   public ViewTestDataFrame(TestDataButtonEditor parentEditor) {
	   this.dataSourceEditor = parentEditor;
	   
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       variableTextArea = new javax.swing.JTextArea();
       updateButton = new javax.swing.JButton();
       cancelButton = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       setTitle("Variables");

       jLabel1.setText("Please enter variables in key-value pairs, then separate them by space");

       variableTextArea.setColumns(20);
       variableTextArea.setRows(5);
       jScrollPane1.setViewportView(variableTextArea);

       variableTextArea.setText(this.dataSourceEditor.getCellEditorValue().toString());
       
       updateButton.setText("Update");
       updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               updateButtonMouseClicked(evt);
           }
       });

       cancelButton.setText("Cancel");
       cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               cancelButtonMouseClicked(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                   .addComponent(jScrollPane1)
                   .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(updateButton)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(cancelButton)
               .addContainerGap())
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(updateButton)
                   .addComponent(cancelButton))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );

       pack();
   }// </editor-fold>                        

   private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {  
	   String text = this.variableTextArea.getText();
	   this.dataSourceEditor.setCellEditorValue(text==null? "" : text);
	   this.setVisible(false);
       this.dispose();
   }                                         

   private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
       this.setVisible(false);
       this.dispose();
   }                                         

//   /**
//    * @param args the command line arguments
//    */
//   public static void main(String args[]) {
//       /* Set the Nimbus look and feel */
//       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//        */
//       try {
//           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//               if ("Nimbus".equals(info.getName())) {
//                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                   break;
//               }
//           }
//       } catch (ClassNotFoundException ex) {
//           java.util.logging.Logger.getLogger(ViewTestDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (InstantiationException ex) {
//           java.util.logging.Logger.getLogger(ViewTestDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (IllegalAccessException ex) {
//           java.util.logging.Logger.getLogger(ViewTestDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//           java.util.logging.Logger.getLogger(ViewTestDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       }
//       //</editor-fold>
//       //</editor-fold>
//
//       /* Create and display the form */
//       java.awt.EventQueue.invokeLater(new Runnable() {
//           public void run() {
//               new ViewTestDataFrame().setVisible(true);
//           }
//       });
//   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton cancelButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton updateButton;
   private javax.swing.JTextArea variableTextArea;
   // End of variables declaration                   
}
